project:
  type: website
  output-dir: docs

website:
  title: "Haley Ventura"
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - NewPage.qmd

format:
  html:
    theme: jouranl
    mainfont: Playfair Display
    fontsize: 1.5rem
    fontcolor: "#710909"
    css: styles.css
    toc: true



