project:
  type: website
  output-dir: docs

website:
  title: "Haley Ventura"
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume

format:
  html:
    theme: minty
    mainfont: Playfair Display
    fontsize: 1.1rem
    fontcolor: "#2B2D42"
    linkcolor: "#D6A2AD"
    css: styles.css
    toc: true



