project:
  type: website
  output-dir: docs

website:
  title: "Haley Ventura"
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume
      - href: H.Ventura Resume_2024_2.15.24.pdf
        text: Resume PDF

format:
  html:
    theme: minty
    mainfont: Playfair Display
    fontsize: 1.1rem
    fontcolor: "#2B2D42"
    linkcolor: "#D6A2AD"
    title-block-banner-color: "#2B2D42"
    toc: true



